QUESTION FOUR

In [8]:

import numpy as np

In [9]:

# Given matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [10]:
# (a) Inversion matrix
inverseMatrix = np.linalg.inv(matrix)
print("(a) Inverse matrix:\n", inverseMatrix)

(a) Inverse matrix:
 [[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [11]:
# (b) Determinant of the matrix
determinant = np.linalg.det(matrix)
print("(b) Determinant of the matrix:", determinant)

(b) Determinant of the matrix: 0.2299999999999999


In [12]:
# (c) Matrix decomposition /eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("(c) Eigenvalues:\n", eigenvalues)
print("    Eigenvectors:\n", eigenvectors)

(c) Eigenvalues:
 [2.04100779 0.82188052 0.13711169]
    Eigenvectors:
 [[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


In [13]:

# (d) Transformation of the matrix
transformationMatrix = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 1]])
transformedMatrix = matrix.dot(transformationMatrix)
print("(d) Transformed matrix:\n", transformedMatrix)

(d) Transformed matrix:
 [[2.  0.6 0.5]
 [0.4 3.  0.8]
 [1.  2.4 1. ]]
