QUESTION FIVE

In [13]:

import numpy as np

In [14]:

#Equations
#2x+3y−z=10
#−3x+y+5z=18
#x+4y−11z=30

# Coefficients (values before or multiplying the unknown)
coefficients = np.array([[2, 3, -1], [-3, 1, 5], [1, 4, -11]])
print(coefficients)

[[  2   3  -1]
 [ -3   1   5]
 [  1   4 -11]]


In [15]:
# Constants
constants = np.array([10, 18, 30])
print(constants)

[10 18 30]


In [16]:
# Solving the equations
Unknowns = np.linalg.solve(coefficients, constants)
print(Unknowns)

[-5.20300752  6.52631579 -0.82706767]


In [17]:

# Solution gives values of x , y and z
x, y, z = Unknowns

print("Unknowns:",Unknowns)
print("x =", x)
print("y =", y)
print("z =", z)

Unknowns: [-5.20300752  6.52631579 -0.82706767]
x = -5.2030075187969915
y = 6.526315789473685
z = -0.8270676691729323
